spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf-8
    username: root
#    password: 123456
    password: root
## close session
  session:
    store-type: none

server:
  port: 8090

## close default configuration
#security:
#  basic:
#    enabled: false

example:
  security:
#   验证码配置---
    code:
#     图片验证码配置---
      image:
#     图片验证码长度
        length: 4
        width: 100
#     需要图片验证的url
#        url: /user/*
#    浏览器配置---
    browser:
      signUpUrl: /demo-signUp.html
#    自定义登录页面
#      loginPage: /demo-signIn.html
#    自定义返回格式 (JSON/REDIRECT)
#      loginType: REDIRECT
    social:
      qq:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        filterProcessesUrl: /login
        providerId: qq