spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf-8
    username: root
#    password: 123456
    password: root
##  close session
  session:
    store-type: redis


server:
  port: 8090
  session:
#  失效时间单位秒:springboot超时时间最少是1分钟(TomcatEmbeddedServletContainerFactory中getSessionTimeoutInMinutes方法)
    timeout: 6000

## close default configuration
security:
  oauth2:
    client:
      clientId: love
      clientSecret: love
#  basic:
#    enabled: false


example:
  security:
#   验证码配置---
    code:
#     图片验证码配置---
      image:
#     图片验证码长度
        length: 4
        width: 100
#     需要图片验证的url
#        url: /user/*
#    浏览器配置---
    browser:
      signOutUrl: /demo-logout.html
      signUpUrl: /demo-signUp.html
#    自定义登录页面
#      loginPage: /demo-signIn.html
#    自定义返回格式 (JSON/REDIRECT)
#      loginType: REDIRECT
    social:
      filterProcessesUrl: /login
      qq:
#      http://www.ictgu.cn/login/qq 回调地址:filterProcessesUrl对应login，providerId对应qq
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        providerId: qq
      weixin:
        app-id: wxfd6965ab1fc6adb2
        app-secret: 66bb4566de776ac699ec1dbed0cc3dd1