security:
  oauth2:
    client:
      clientId: love2
      clientSecret: love2
      user-authorization-uri: http://localhost:9999/server/oauth/authorize
      access-token-uri:  http://localhost:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:9999/server/oauth/token_key
server:
  port: 8060
  context-path: /client2

